// Mocks generated by Mockito 5.4.6 from annotations
// in xepa_frontend/test/features/shopping_list/data/repositories/shopping_list_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:xepa_frontend/features/shopping_list/data/datasources/i_shopping_list_datasource.dart'
    as _i5;
import 'package:xepa_frontend/features/shopping_list/data/models/comparison_result_model.dart'
    as _i4;
import 'package:xepa_frontend/features/shopping_list/data/models/shopping_list_item_model.dart'
    as _i3;
import 'package:xepa_frontend/features/shopping_list/data/models/shopping_list_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeShoppingListModel_0 extends _i1.SmartFake
    implements _i2.ShoppingListModel {
  _FakeShoppingListModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShoppingListItemModel_1 extends _i1.SmartFake
    implements _i3.ShoppingListItemModel {
  _FakeShoppingListItemModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComparisonResultModel_2 extends _i1.SmartFake
    implements _i4.ComparisonResultModel {
  _FakeComparisonResultModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IShoppingListDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIShoppingListDataSource extends _i1.Mock
    implements _i5.IShoppingListDataSource {
  MockIShoppingListDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.ShoppingListModel>> getShoppingLists() =>
      (super.noSuchMethod(
            Invocation.method(#getShoppingLists, []),
            returnValue: _i6.Future<List<_i2.ShoppingListModel>>.value(
              <_i2.ShoppingListModel>[],
            ),
          )
          as _i6.Future<List<_i2.ShoppingListModel>>);

  @override
  _i6.Future<_i2.ShoppingListModel> getShoppingListById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getShoppingListById, [id]),
            returnValue: _i6.Future<_i2.ShoppingListModel>.value(
              _FakeShoppingListModel_0(
                this,
                Invocation.method(#getShoppingListById, [id]),
              ),
            ),
          )
          as _i6.Future<_i2.ShoppingListModel>);

  @override
  _i6.Future<_i2.ShoppingListModel> createShoppingList(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#createShoppingList, [name]),
            returnValue: _i6.Future<_i2.ShoppingListModel>.value(
              _FakeShoppingListModel_0(
                this,
                Invocation.method(#createShoppingList, [name]),
              ),
            ),
          )
          as _i6.Future<_i2.ShoppingListModel>);

  @override
  _i6.Future<bool> deleteShoppingList(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteShoppingList, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i3.ShoppingListItemModel> addItemToList(
    int? listId,
    int? productId,
    double? quantity,
    String? notes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addItemToList, [
              listId,
              productId,
              quantity,
              notes,
            ]),
            returnValue: _i6.Future<_i3.ShoppingListItemModel>.value(
              _FakeShoppingListItemModel_1(
                this,
                Invocation.method(#addItemToList, [
                  listId,
                  productId,
                  quantity,
                  notes,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.ShoppingListItemModel>);

  @override
  _i6.Future<bool> removeItemFromList(int? listId, int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeItemFromList, [listId, itemId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.ShoppingListModel> updateShoppingList(
    int? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShoppingList, [id, updates]),
            returnValue: _i6.Future<_i2.ShoppingListModel>.value(
              _FakeShoppingListModel_0(
                this,
                Invocation.method(#updateShoppingList, [id, updates]),
              ),
            ),
          )
          as _i6.Future<_i2.ShoppingListModel>);

  @override
  _i6.Future<_i4.ComparisonResultModel> compareShoppingList(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#compareShoppingList, [id]),
            returnValue: _i6.Future<_i4.ComparisonResultModel>.value(
              _FakeComparisonResultModel_2(
                this,
                Invocation.method(#compareShoppingList, [id]),
              ),
            ),
          )
          as _i6.Future<_i4.ComparisonResultModel>);
}
