// Mocks generated by Mockito 5.4.6 from annotations
// in xepa_frontend/test/features/shopping_list/domain/usecases/compare_shopping_list_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:xepa_frontend/features/shopping_list/domain/entities/comparison_result.dart'
    as _i4;
import 'package:xepa_frontend/features/shopping_list/domain/entities/shopping_list.dart'
    as _i2;
import 'package:xepa_frontend/features/shopping_list/domain/entities/shopping_list_item.dart'
    as _i3;
import 'package:xepa_frontend/features/shopping_list/domain/repositories/i_shopping_list_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeShoppingList_0 extends _i1.SmartFake implements _i2.ShoppingList {
  _FakeShoppingList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShoppingListItem_1 extends _i1.SmartFake
    implements _i3.ShoppingListItem {
  _FakeShoppingListItem_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComparisonResult_2 extends _i1.SmartFake
    implements _i4.ComparisonResult {
  _FakeComparisonResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IShoppingListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIShoppingListRepository extends _i1.Mock
    implements _i5.IShoppingListRepository {
  MockIShoppingListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.ShoppingList>> getShoppingLists() =>
      (super.noSuchMethod(
            Invocation.method(#getShoppingLists, []),
            returnValue: _i6.Future<List<_i2.ShoppingList>>.value(
              <_i2.ShoppingList>[],
            ),
          )
          as _i6.Future<List<_i2.ShoppingList>>);

  @override
  _i6.Future<_i2.ShoppingList> getShoppingListById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getShoppingListById, [id]),
            returnValue: _i6.Future<_i2.ShoppingList>.value(
              _FakeShoppingList_0(
                this,
                Invocation.method(#getShoppingListById, [id]),
              ),
            ),
          )
          as _i6.Future<_i2.ShoppingList>);

  @override
  _i6.Future<_i2.ShoppingList> createShoppingList(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#createShoppingList, [name]),
            returnValue: _i6.Future<_i2.ShoppingList>.value(
              _FakeShoppingList_0(
                this,
                Invocation.method(#createShoppingList, [name]),
              ),
            ),
          )
          as _i6.Future<_i2.ShoppingList>);

  @override
  _i6.Future<bool> deleteShoppingList(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteShoppingList, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i3.ShoppingListItem> addItemToList(
    int? listId,
    int? productId,
    double? quantity,
    String? notes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addItemToList, [
              listId,
              productId,
              quantity,
              notes,
            ]),
            returnValue: _i6.Future<_i3.ShoppingListItem>.value(
              _FakeShoppingListItem_1(
                this,
                Invocation.method(#addItemToList, [
                  listId,
                  productId,
                  quantity,
                  notes,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.ShoppingListItem>);

  @override
  _i6.Future<bool> removeItemFromList(int? listId, int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeItemFromList, [listId, itemId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.ShoppingList> updateShoppingList(
    int? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShoppingList, [id, updates]),
            returnValue: _i6.Future<_i2.ShoppingList>.value(
              _FakeShoppingList_0(
                this,
                Invocation.method(#updateShoppingList, [id, updates]),
              ),
            ),
          )
          as _i6.Future<_i2.ShoppingList>);

  @override
  _i6.Future<_i4.ComparisonResult> compareShoppingList(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#compareShoppingList, [id]),
            returnValue: _i6.Future<_i4.ComparisonResult>.value(
              _FakeComparisonResult_2(
                this,
                Invocation.method(#compareShoppingList, [id]),
              ),
            ),
          )
          as _i6.Future<_i4.ComparisonResult>);
}
